# Initially generated by GitHub Copilot.
"""Public runner surface for Sefaria and AJF exports."""

from mb_cmn import bib_locales as tbn
from mb_sefaria import mam4ajf_handlers
from mb_sefaria import mam4sef_handlers
from mb_sefaria import mam4sef_or_ajf


def build_sef_variant():
    """Build the variant dict for Sefaria export output."""
    return {
        "variant-vtrad": tbn.VT_SEF,
        "variant-handlers": mam4sef_handlers.HANDLERS,
    }


def build_ajf_variant():
    """Build the variant dict for AJF export output."""
    return {
        "variant-vtrad": tbn.VT_BHS,
        "variant-handlers": mam4ajf_handlers.HANDLERS,
        "variant-path-qual": "vpq-ajf",
        "variant-exclude-header-from-csv": True,
        "variant-include-abcants": True,
    }


def run_sef(overrides=None):
    """Create the Sefaria MAM from the XML MAM."""
    variant = build_sef_variant()
    if overrides:
        variant.update(overrides)
    mam4sef_or_ajf.main_helper(variant)


def run_ajf(overrides=None):
    """Create the AJF MAM from the XML MAM."""
    variant = build_ajf_variant()
    if overrides:
        variant.update(overrides)
    mam4sef_or_ajf.main_helper(variant)


def run_both_sef_and_ajf(overrides=None):
    """Create both the Sefaria and AJF MAM variants from the XML MAM."""
    run_sef(overrides=overrides)
    run_ajf(overrides=overrides)
