# Initially generated by GitHub Copilot.
"""Find <letter-small> elements in Job and write a report.

When run from the MAM-simple repo root:

    python py-examples/main_letter_small_job_example.py
"""

from mb_misc import letter_small_job


def main():
    """Find <letter-small> elements in Job."""
    letter_small_job.almost_main("xml-vtrad-mam/Job.xml")


if __name__ == "__main__":
    main()
