# Initially generated by GitHub Copilot.
"""Create Sefaria and/or AJF MAM variants from the MAM-simple JSON data."""

import argparse
import sys

from mb_sefaria import mam4sef_runners

_OVERRIDES = {
    "variant-input-base": ".",
    "variant-output-root": "py-examples/out/sefaria",
}


def run_sef():
    """Create the Sefaria MAM from the MAM-simple JSON data."""
    mam4sef_runners.run_sef(overrides=_OVERRIDES)


def run_ajf():
    """Create the AJF MAM from the MAM-simple JSON data."""
    mam4sef_runners.run_ajf(overrides=_OVERRIDES)


def run_both_sef_and_ajf():
    """Create both Sefaria and AJF MAM variants from the MAM-simple JSON data."""
    mam4sef_runners.run_both_sef_and_ajf(overrides=_OVERRIDES)


def _build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    mutex = parser.add_mutually_exclusive_group()
    mutex.add_argument(
        "--both-sef-and-ajf",
        action="store_true",
        help="Generate both Sefaria and AJF outputs.",
    )
    mutex.add_argument(
        "--just-ajf",
        action="store_true",
        help="Generate only AJF outputs.",
    )
    return parser


def _runner_from_args(args):
    if args.just_ajf:
        return run_ajf
    if args.both_sef_and_ajf:
        return run_both_sef_and_ajf
    return run_sef


def _run_with_passthrough_argv(runner, passthrough_argv):
    old_argv = sys.argv
    try:
        sys.argv = [old_argv[0], *passthrough_argv]
        runner()
    finally:
        sys.argv = old_argv


def main(argv=None):
    """Create Sefaria output by default, with explicit selectors for AJF modes."""
    if argv is None:
        argv = sys.argv[1:]
    args, passthrough_argv = _build_parser().parse_known_args(argv)
    runner = _runner_from_args(args)
    _run_with_passthrough_argv(runner, passthrough_argv)


if __name__ == "__main__":
    main()
