# Initially generated by GitHub Copilot.
"""Convert MAM-simple XML data to per-book OSIS XML files."""

from mb_cmn import bib_locales as tbn
from osis import osis_runner

_PATHS = {
    "input_xml_dir": "xml-vtrad-bhs",
    "output_book_dir": "py-examples-out/osis",
}


def main():
    """Create per-book OSIS XML from MAM-simple data."""
    osis_runner.almost_main(tbn.ALL_BK39_IDS, _PATHS)


if __name__ == "__main__":
    main()
