# Initially generated by GitHub Copilot.
"""Find <letter-small> elements in Job and write a report.

When run from the MAM-simple repo root (e.g. as a standalone example):

    python py-examples/main_letter_small_job.py

This file is also used in the MAM-basics pipeline.
"""

import xml.etree.ElementTree as ET


def find_letter_small_in_job(xml_path, out_fp):
    for root_child in ET.parse(xml_path).getroot():
        for verse in root_child.iter("verse"):
            for el in verse.iter("letter-small"):
                out_fp.write(f"{verse.attrib['osisID']}\t{el.attrib['text']}\n")


if __name__ == "__main__":
    with open("out/letter-small.txt", "w", encoding="utf-8") as fp:
        find_letter_small_in_job("out/xml-vtrad-mam/Job.xml", fp)
