# Initially generated by GitHub Copilot.
"""Create Sefaria MAM variant from the MAM-simple JSON data."""

from mb_sefaria import mam4sef_runners

_OVERRIDES = {
    "variant-input-base": ".",
    "variant-output-root": "py-examples-out/sefaria",
}


def main():
    """Create the Sefaria MAM from the MAM-simple JSON data."""
    mam4sef_runners.run_sef(overrides=_OVERRIDES)


if __name__ == "__main__":
    main()
